import type { AchievementDef } from '@/game/types'

export const ACHIEVEMENTS: readonly AchievementDef[] = [
  {
    id: 'first-blood',
    name: 'First Blood',
    description: 'Score your first kill.',
    icon: '🩸',
    condition: { type: 'totalKills', threshold: 1 },
  },
  {
    id: 'finger-workout',
    name: 'Finger Workout',
    description: 'Smash the zombie 100 times.',
    icon: '👆',
    condition: { type: 'clicks', threshold: 100 },
  },
  {
    id: 'fresh-meat',
    name: 'Fresh Meat',
    description: 'Rack up 100 total kills.',
    icon: '🧟',
    condition: { type: 'totalKills', threshold: 100 },
  },
  {
    id: 'bat-basics',
    name: 'Bat Basics',
    description: 'Own your first Baseball Bat.',
    icon: '🏏',
    condition: { type: 'buildingOwned', buildingId: 'cursor', count: 1 },
  },
  {
    id: 'granny-guard',
    name: 'Granny Guard',
    description: 'Recruit a Shotgun Granny.',
    icon: '👵',
    condition: { type: 'buildingOwned', buildingId: 'grandma', count: 1 },
  },
  {
    id: 'click-crazy',
    name: 'Click Crazy',
    description: 'Smash the zombie 1,000 times.',
    icon: '💀',
    condition: { type: 'clicks', threshold: 1000 },
  },
  {
    id: 'still-breathing',
    name: 'Still Breathing',
    description: 'Survive to 1,000 total kills.',
    icon: '🛡️',
    condition: { type: 'totalKills', threshold: 1000 },
  },
  {
    id: 'armory-starter',
    name: 'Armory Starter',
    description: 'Own 10 weapons total.',
    icon: '🔫',
    condition: { type: 'totalBuildings', threshold: 10 },
  },
  {
    id: 'bat-hoarder',
    name: 'Bat Hoarder',
    description: 'Stockpile 5 Baseball Bats.',
    icon: '⚾',
    condition: { type: 'buildingOwned', buildingId: 'cursor', count: 5 },
  },
  {
    id: 'granny-squad',
    name: 'Granny Squad',
    description: 'Deploy 5 Shotgun Grannies.',
    icon: '👵',
    condition: { type: 'buildingOwned', buildingId: 'grandma', count: 5 },
  },
  {
    id: 'pit-digger',
    name: 'Pit Digger',
    description: 'Build your first Pit Trap.',
    icon: '🕳️',
    condition: { type: 'buildingOwned', buildingId: 'farm', count: 1 },
  },
  {
    id: 'upgrade-initiate',
    name: 'Upgrade Initiate',
    description: 'Purchase your first upgrade.',
    icon: '⬆️',
    condition: { type: 'upgradesOwned', threshold: 1 },
  },
  {
    id: 'fully-loaded',
    name: 'Fully Loaded',
    description: 'Own 5 upgrades.',
    icon: '📦',
    condition: { type: 'upgradesOwned', threshold: 5 },
  },
  {
    id: 'killing-machine',
    name: 'Killing Machine',
    description: 'Reach 100 kills per second.',
    icon: '⚡',
    condition: { type: 'cps', threshold: 100 },
  },
  {
    id: 'weapon-collector',
    name: 'Weapon Collector',
    description: 'Own 25 weapons total.',
    icon: '🗡️',
    condition: { type: 'totalBuildings', threshold: 25 },
  },
  {
    id: 'mass-extermination',
    name: 'Mass Extermination',
    description: 'Amass 10,000 total kills.',
    icon: '☠️',
    condition: { type: 'totalKills', threshold: 10_000 },
  },
  {
    id: 'click-fury',
    name: 'Click Fury',
    description: 'Smash the zombie 10,000 times.',
    icon: '👊',
    condition: { type: 'clicks', threshold: 10_000 },
  },
  {
    id: 'factory-online',
    name: 'Factory Online',
    description: 'Open an Ammo Factory.',
    icon: '🏭',
    condition: { type: 'buildingOwned', buildingId: 'factory', count: 1 },
  },
  {
    id: 'safe-house',
    name: 'Safe House',
    description: 'Establish a Safe House.',
    icon: '🏠',
    condition: { type: 'buildingOwned', buildingId: 'temple', count: 1 },
  },
  {
    id: 'apocalypse-now',
    name: 'Apocalypse Now',
    description: 'Reach 100,000 total kills.',
    icon: '🌋',
    condition: { type: 'totalKills', threshold: 100_000 },
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Reach 1,000 kills per second.',
    icon: '🔥',
    condition: { type: 'cps', threshold: 1000 },
  },
  {
    id: 'veteran-clicker',
    name: 'Veteran Clicker',
    description: 'Smash the zombie 50,000 times.',
    icon: '🎖️',
    condition: { type: 'clicks', threshold: 50_000 },
  },
  {
    id: 'million-strong',
    name: 'Million Strong',
    description: 'Amass 1,000,000 total kills.',
    icon: '💥',
    condition: { type: 'totalKills', threshold: 1_000_000 },
  },
  {
    id: 'extinction-event',
    name: 'Extinction Event',
    description: 'Amass 10,000,000 total kills.',
    icon: '🌑',
    condition: { type: 'totalKills', threshold: 10_000_000 },
  },
  {
    id: 'armory-commander',
    name: 'Armory Commander',
    description: 'Own 50 weapons total.',
    icon: '🛡️',
    condition: { type: 'totalBuildings', threshold: 50 },
  },
  {
    id: 'war-chest',
    name: 'War Chest',
    description: 'Own 100 weapons total.',
    icon: '📦',
    condition: { type: 'totalBuildings', threshold: 100 },
  },
  {
    id: 'arsenal-master',
    name: 'Arsenal Master',
    description: 'Own 20 upgrades.',
    icon: '🧰',
    condition: { type: 'upgradesOwned', threshold: 20 },
  },
  {
    id: 'killstorm',
    name: 'Killstorm',
    description: 'Reach 10,000 kills per second.',
    icon: '🌪️',
    condition: { type: 'cps', threshold: 10_000 },
  },
  {
    id: 'iron-fingers',
    name: 'Iron Fingers',
    description: 'Smash the zombie 100,000 times.',
    icon: '🦾',
    condition: { type: 'clicks', threshold: 100_000 },
  },
  {
    id: 'first-ascension',
    name: 'First Ascension',
    description: 'Reach Survivor Rank 1.',
    icon: '⬆️',
    condition: { type: 'prestigeLevel', threshold: 1 },
  },
  {
    id: 'seasoned-survivor',
    name: 'Seasoned Survivor',
    description: 'Reach Survivor Rank 5.',
    icon: '🏅',
    condition: { type: 'prestigeLevel', threshold: 5 },
  },
  {
    id: 'landmine-king',
    name: 'Landmine King',
    description: 'Deploy 10 Landmine Fields.',
    icon: '💣',
    condition: { type: 'buildingOwned', buildingId: 'mine', count: 10 },
  },
  {
    id: 'flame-wall',
    name: 'Flame Wall',
    description: 'Build 5 Flamethrower Towers.',
    icon: '🔥',
    condition: { type: 'buildingOwned', buildingId: 'wizardTower', count: 5 },
  },
  {
    id: 'war-rig-rollout',
    name: 'War Rig Rollout',
    description: 'Deploy a War Rig.',
    icon: '🚛',
    condition: { type: 'buildingOwned', buildingId: 'warRig', count: 1 },
  },
  {
    id: 'sky-fire',
    name: 'Sky Fire',
    description: 'Bring an Orbital Laser online.',
    icon: '🛰️',
    condition: { type: 'buildingOwned', buildingId: 'orbitalLaser', count: 1 },
  },
  {
    id: 'first-duel',
    name: 'First Duel',
    description: 'Complete your first duel.',
    icon: '⚔️',
    condition: { type: 'duelsPlayed', threshold: 1 },
  },
  {
    id: 'duel-victor',
    name: 'Duel Victor',
    description: 'Win your first duel.',
    icon: '🏆',
    condition: { type: 'duelWins', threshold: 1 },
  },
  {
    id: 'duel-contender',
    name: 'Duel Contender',
    description: 'Fight in 5 duels.',
    icon: '🥊',
    condition: { type: 'duelsPlayed', threshold: 5 },
  },
  {
    id: 'duel-champion',
    name: 'Duel Champion',
    description: 'Win 5 duels.',
    icon: '👑',
    condition: { type: 'duelWins', threshold: 5 },
  },
  {
    id: 'duel-gladiator',
    name: 'Duel Gladiator',
    description: 'Fight in 25 duels.',
    icon: '🗡️',
    condition: { type: 'duelsPlayed', threshold: 25 },
  },
  {
    id: 'duel-legend',
    name: 'Duel Legend',
    description: 'Win 25 duels.',
    icon: '⭐',
    condition: { type: 'duelWins', threshold: 25 },
  },
  {
    id: 'stalemate',
    name: 'Stalemate',
    description: 'Draw a duel.',
    icon: '🤝',
    condition: { type: 'duelDraws', threshold: 1 },
  },
  {
    id: 'grit-and-glory',
    name: 'Grit and Glory',
    description: 'Lose 5 duels and keep coming back.',
    icon: '🩹',
    condition: { type: 'duelLosses', threshold: 5 },
  },
] as const

export const ACHIEVEMENT_BY_ID: Readonly<Record<string, AchievementDef>> = Object.fromEntries(
  ACHIEVEMENTS.map((achievement) => [achievement.id, achievement]),
)

export function getAchievement(id: string): AchievementDef | undefined {
  return ACHIEVEMENT_BY_ID[id]
}
